### ISSUE TITLE
Figure out encoding warning message

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#10]
We're getting this message: 

```
No encoding supplied: defaulting to UTP-8.
```

We need to figure out what's going on there.

**Comment by leighseverson** [comment]
Everything online about this message is in the context of the `httr` package, and it looks like the message shows up in some of the code for that package (https://github.com/hadley/httr/blob/master/R/content-parse.r). 

Very unclear what the `httr` package has to do with the code we're running.

**Comment by geanders** [comment]
The `httr` package has the `GET` function, which is being used by several of the `ghcnd_*` functions (just buried deep in helper functions). That's what's FTP-ing the data in from NOAA. [Here's](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html) a quick start for `http`. We don't need to understand it completely, but it would be helpful to have some idea why we're getting that message and if it's benign.

**Comment by geanders** [comment]
There's also a function right after the `GET` function called `utcf8`. I couldn't figure out what package it's from, but maybe this is what's giving the warning. The `GET` function in `ghcnd_GET` is wrapped in `suppressWarnings`, so maybe we shouldn't be getting any warnings from that at all.

**Comment by geanders** [comment]
If we figure out that this message isn't a worry for this data, we can can some of the code so that warnings / messages don't get printed from that part of the function. Let's make sure we figure it out first, though.

**Comment by geanders** [comment]
Okay, so I've wrapped this with a `suppressWarnings` so we don't get the warning, but it wouldn't hurt to see if we can figure it out...

**Comment by geanders** [comment]
Well, I thought I suppressed it, but maybe not...
