### ISSUE TITLE
Error in UseMethod("select_") :    no applicable method for 'select_' applied to an object of class "c('meteo_coverage', 'list')"

### ISSUE THREAD

**Issue by pirolli** [leighseverson/countyweather#102]
# Tried this simple example.  NOAA key set appropriately.  Tried installing from CRAN and from GitHub.  Same message.

> library(countyweather)
> sf<-daily_fips(fips='06075', date_min='2020-01-01',date_max='2020-12-30',var='prcp')
Getting daily weather data for San Francisco County, California. This may take a while.
Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "c('meteo_coverage', 'list')"

> version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out

**Comment by woodhouse123** [comment]
I am getting the same error...

**Comment by leighseverson** [comment]
Hey there, please try again after reinstalling the package from GitHub - I think this should work now.
