### ISSUE TITLE
Create mapping function

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#13]
It would be very cool if we could come up with a function that, for a particular FIPS, would plot the locations of all the monitors identified by `ncdc_station` for the county and use color or something to show percent missing for the study period.

For this, we'll need to look into how to plot points within a US county in R. We might be able to do it using some of the more straightforward mapping functionality with `ggplot2`. You might want to check out the "Mapping in R" notes from class-- I think I mapped some stuff in Baltimore county with that. However, if that doesn't link directly with FIPS code, then we might want to do something else. I don't think that we want to include shape files for every county in the package-- that would be the "from scratch" way to do this, but it would make the package really huge, and there has to be some way to tap into county-level mapping that someone else has prepared, I'm thinking. 

This would be great, though, because then we (and others) could plot out a multi-page pdf with each study county and monitor locations, with percent non-missing, as a check when creating datasets.

**Comment by leighseverson** [comment]
Added a first attempt at this to weather_fips new.R - still needs more work! (include county boundaries, combine with weather_fips() (?), etc - by more work I mean a lot more work)

**Comment by geanders** [comment]
I'll take a look...

**Comment by leighseverson** [comment]
I think `station_map` has this covered (for now!)
