### ISSUE TITLE
Break `weather_fips` into more smaller function

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#15]
Part of this we might want to use in other ways, so it will be good if we can break this down into some smaller functions, and then use `weather_fps` to put the different parts together.

**Comment by geanders** [comment]
One big split is to have separate subfunctions for (1) getting matching weather station IDs for each county and (2) pulling and cleaning the data once you have those IDs.

**Comment by geanders** [comment]
So, I've figured out that the `rnoaa` `ghcnd_search` function does a lot of what we want to do for an individual station. I think we may want to convert `weather_fips` so that it uses that, plus some functions we came up with at the conference that I think are going into `rnoaa`, to do some of the subset-type tasks in that function, so that `weather_fips` gets the big picture stuff we want to do done, but using other sub functions instead of all the pieces of code for all the tasks being in one big function. I can explain more when we meet tomorrow...

**Comment by leighseverson** [comment]
My first attempt at this is in weather_fips new.R !
