### ISSUE TITLE
Generalize date ranges

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#17]
Let's change so the user can pick their own upper and lower date limits in `weather_fips`. This will mean changing this line: 

```
dplyr::filter(maxdate >= "2012-12-31" & mindate <= "1999-01-01")
```

so that the dates it's checking against are function options rather than hardwired values.

**Comment by geanders** [comment]
Same thing for the data coverage option in this function.

**Comment by leighseverson** [comment]
I made the date range and the data coverage values options in the `fips_stations` function, but I'm having trouble making the options *optional*. 

For example, I tried 
 `if(is.null(datemin)){
     datemin <- "1900-01-01"
    } else {
      dplyr::filter(tot_df, mindate <= datemin)
    }`
