### ISSUE TITLE
tavg seems like a 'rare' variable 

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#19]
Including tavg in the coverage requirements tends to kick out all of the stations for a particular fips

**Comment by geanders** [comment]
I think you're right. We can check with some weather people, but I think that it's often okay to average `tmin` and `tmax` to get a mean daily temperature, so we might want to do that, instead. (Like, not try to get `tavg` from the monitors, but instead add this average of `tmin` and `tmax` as part of the post-cleaning.)

**Comment by leighseverson** [comment]
Should this calculation of TAVG be something we include in `countyweather`?
