### ISSUE TITLE
problem with meteo_coverage() verbose = TRUE 

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#20]
unless I specify that verbose = FALSE in meteo_coverage(), I get the error: 
`Error in sprintf("  Total number of observations: %s\n\n", comma(nrow(.))) : could not find function "comma"`

**Comment by geanders** [comment]
Okay, I'll move this to the issues page of our `rnoaa` fork and look into it. You can close this issue (I think I might not have access to close issues since this is your repo).
