### ISSUE TITLE
Clarify `coverage` in documentation 

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#22]
For `weather_fips`, does this mean that you kick out stations where *all* three weather variables don't meet the coverage limit, or do you check and keep weather variables separately for coverage? (For example, if you have a monitor with 100% temperature coverage but no precipitation, would you keep it for temperature, or throw it out since it doesn't meet the coverage requirement for all variables? I think we want to do the first rather than the second if we can.)

**Comment by geanders** [comment]
Yeah, let's change this so that `filter_coverage` checks the coverage of every weather variable and will let a station that has high coverage for precipitation, but nothing for temperature, still contribution to the `prcp` average. It might not be completely straightforward to do that, but I'll think about how we could get it to work. Otherwise, we're loosing loads of stations that only measure precipitation but not temperature, which is unfortunate.

**Comment by leighseverson** [comment]
I think this is working - we're grouping stations by weather variable before filtering by coverage
