### ISSUE TITLE
Consider changing `min_date` and `max_date` argument names.

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#24]
In `meteo_pull_monitor`, I'm using `date_min` and `date_max`, I think to correspond with the argument names in some of the `ghncd_*` functions. It doesn't matter much to me which we use, but if the arguments mean the same thing in different functions, it will make it easier for the user if we're consistent with our argument names.

**Comment by leighseverson** [comment]
Agreed - I changed mine to `date_min` and `date_max`!

**Comment by geanders** [comment]
Excellent.
