### ISSUE TITLE
Make `sqldf` functions optional rather than the default

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#30]
If we do that, we can make that package "Suggests" instead of "Depends", and it would keep all the users from having to install that package.

**Comment by geanders** [comment]
This also crashed my R session. I'll see if I can figure out why...

**Comment by geanders** [comment]
We also might want to see if we can use some of Hadley's stuff as an alternative. Is the goal to have something that will work well with a SQL database? Is so, I think some of his packages let you tap directly into a database rather than working from an R dataframe. His stuff tends to be quite robust by the time he puts it out for folks to use, so I think we'd (hopefully) keep dependence problems to a minimum if we could use his stuff rather than alternatives.

**Comment by geanders** [comment]
Yep. [Here](http://www2.stat.duke.edu/~cr173/Sta523_Fa14/slides/2014-10-20-dplyr_sql.html#1) are some course notes to check out talking about how to use `dplyr` as a front end for a SQL database. Do you think we could use `dplyr` instead of `sqldf` for what you're trying to do?

**Comment by leighseverson** [comment]
Yes - completely thanks to your code SQL is gone thank goodness! Good riddance
