### ISSUE TITLE
Re-think `data_coverage` option in `fips_station`

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#32]
I think that the `data_coverage` column in the dataframe we get back from the `ncdc_stations` in `fips_station` is the coverage over the **whole** period that the monitor covers. That means that, in theory, if we use it as a filter, we could filter out stations that we actually want. For example, if a station had 100% coverage over 2010--2012, but the station is report for 1900--2016 and has 50% coverage over that whole period, I think that this `ncdc_stations` is giving us the 50% coverage, even though we wouldn't want to filter out the station. So we may have to get the actual data before we can do any filtering by coverage, which means we shouldn't have it as an argument in `fips_stations`, just in `weather_fips`.

**Comment by leighseverson** [comment]
Agreed - it looks like this is fixed.
