### ISSUE TITLE
Finding data for statistics options other than "mean" in streamdata function 

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#40]
Out of the available [stat codes](http://help.waterdata.usgs.gov/code/stat_cd_nm_query?stat_nm_cd=%25&fmt=html), it seems like there's only data for the daily mean ("00003") available.

**Comment by geanders** [comment]
Rod wrote some code on this for his example for the hackathon. I think he came to the same conclusion, but wrote his own code to pull the 95th percentile for each monitor. The data's available from USGS, so we can get it, just maybe not without writing the function ourself.

**Comment by geanders** [comment]
Also, one of the undergraduates doing research with me is looking into the stream gage data a bit more and might be able to give us some more tips for this part.

**Comment by leighseverson** [comment]
Saving this for `countyweather` v 2.0...
