### ISSUE TITLE
For hourly, do we want to do anything to clean the data when we first bring it in?

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#43]
It looks like the dataframe returned by `isd` has *lots* of variables, including plenty that are flags for the data quality. We should read the documentation about the data that you've included the ftp link for in the code. We may want to use some of these flags to set some questionable measurements to missing when we bring the different variables in at this stage.

**Comment by leighseverson** [comment]
When I'm reading in "wind_speed" and "wind_speed_quality" for an example of this in the vignette, both variables are coming in as logical data types (`lgl`), and it looks like they're all missing. When I bring in just "wind_speed", `hourly_fips` works fine.

**Comment by geanders** [comment]
I think we've resolved this.
