### ISSUE TITLE
Fix NSE issues

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#52]
For the daily functions: 

- `ave_weather` (`gather`)
- `filter_coverage` (`gather`)
- `fips_stations` (`mutate`, `filter`, `select`)
- `station_radius`
- `stationmap_fips` (`gather`, `mutate`, `spread`)

**Comment by geanders** [comment]
I think the lurking ones for this are now all in the `filter_hourly` function and are all related to `gather_` calls.

**Comment by leighseverson** [comment]
Just ran check() - still some things to fix, but I think NSE problems are taken care of now.
