### ISSUE TITLE
problem with meteo_pull_monitors 

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#57]
When I try to run functions/code involving meteo_pull_monitors, I'm getting the following error message: 

`Error: 'meteo_pull_monitors' is not an exported object from 'namespace:rnoaa'`

**Comment by geanders** [comment]
Are you sure you have the rnoaa version from ropenscilabs rather than CRAN or ropensci? Double check that (reinstall from GitHub and restart R if you're not sure), then let me know if you still have problems.
________________________________

**Comment by leighseverson** [comment]
restarting R did the trick!
