### ISSUE TITLE
isd_monitors_data data types 

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#61]
In isd_monitors_data(), columns sometimes come in from different monitors as different data types - right now I'm changing the ones that come up most often as errors by hand to numeric in the function, but I want to be able to do this for ALL possible hourly variables.

**Comment by leighseverson** [comment]
Here's what the error looks like when this problem arises: 

`Error: Can not automatically convert from character to numeric in column "ceiling_height".`

**Comment by geanders** [comment]
You're working on a local version where you've pulled all the recent GitHub changes, right? I was coming across this same error in using the package for some of the hurricane work, and I remember I did something to get things working for that, although perhaps it wasn't general enough for this issue, as well. Double-check that your local is up-to-date with your GitHub branch, and if you still get this error, then put in the code you were running when you got it so we can replicate it and figure it out.
