### ISSUE TITLE
Top-level files to be moved

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#63]
There are a few directories and files in the top level of the package that we'll want to move if we can, but I wanted to check first to make sure it won't mess anything up to move them: 

- `Untitled-figure/` folder: Are we using these figures anywhere (for example, in a vignette or a presentation), or are they just example figures from trying out some code that we could delete?
- `pngs` folder: Same thing.
- `county_centers.rda`: Should the file of this that's in the main package directory replace the same file in the `data/` directory?

**Comment by leighseverson** [comment]
I think I was using the figures in the 

- I think I was using the figures in the `Untitled-figure/` folder for my working with online data in R presentation they're not related to the package and can be moved or deleted! 
- Same for the `pngs` folder 
- yes - I think so!

**Comment by geanders** [comment]
Great. I'll take those out, and then I'll do a pull request that incorporates my latest changes with your latest version, which I just merge in. I think this version is pretty close to passing all the CRAN checks.

________________________________
