### ISSUE TITLE
Output: one dataframe, or write one file / county?

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#7]
> Do we want weather info for each county in a separate file? (vs. one huge dataframe)

Right now, I'm thinking we might want to allow this as a user option. For our research, we have so many counties, I think we definitely will need to be able to write out separate files. One idea is to have separate files be the default as soon as you get more than a certain number of counties, to have a single dataframe be the default for just one or a few counties, and to have the option for a user to do either if he specifies.

**Comment by leighseverson** [comment]
For now I have `county_timeseries` working so that it creates multiple files no matter the number of counties specified, but I like the idea of it outputting just one dataframe for only a few counties! I'll keep working on this.
