### ISSUE TITLE
Problems recognizing county_radius as an exported object

### ISSUE THREAD

**Issue by leighseverson** [leighseverson/countyweather#71]
I added county_radius.rda to the data folder, and added a description of the dataframe to data.R. When I try to run:

`radius_data <- countyweather::county_radius`

in the `isd_fips_stations()` function in hourly_helpers.R, I'm getting: 

`Error: 'county_radius' is not an exported object from 'namespace:countyweather'` 

Not a huge issue, I'm just not sure what else I need to do to export the `county_radius` data. I'm reading the raw data from a downloaded file, and not from the web - is that an issue?

**Comment by geanders** [comment]
It might just not be loaded yet. Try `load_all()` and see if you still have the problem. I just did that and things worked okay in my R console, but I'm curious if we'll still have problems running within a function. In any case, try re-loading everything in your package and see if it works.


I've been going through your other changes, too, by the way-- great work on those!

________________________________

**Comment by leighseverson** [comment]
You're right - it works fine, now!
