### ISSUE TITLE
Bug with hourly weather functions

### ISSUE THREAD

**Issue by geanders** [leighseverson/countyweather#75]
I'm getting an error when I run: 

```
andrew_hourly <- hourly_fips(fips = "12086", year = 1992,
                           var = c("wind_speed", "temperature"))
```

Here is the error: 

``` 
Error in isd_monitors_data(fips = fips, year = x, var = var, radius = radius) : 
  unused argument (radius = radius) 
```

It looks like the `isd_monitors_data` function does not take a `radius` argument, but we're trying to pass it one in the `hourly_df` function (line 111 of "hourly_fips.R").

**Comment by leighseverson** [comment]
This is working for me now - I think I caught them all!
