### ISSUE TITLE
googleapis

### ISSUE THREAD

**Issue by muhusmanmirza** [leighseverson/countyweather#97]
I was trying to run the following command from the vignettes:

andrew_precip <- daily_fips(fips = "12086", date_min = "1992-08-01", date_max = "1992-08-31", var = "prcp")

I got the following error:
Unable to pull weather data for FIPS code 12086 for the specified percent coverage, date range, and/or weather variables.
Warning messages:
1: In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=25.610494,-80.499045&zoom=9&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false': HTTP status was '403 Forbidden'

Can you please help me??

**Comment by leighseverson** [comment]
Hey there, this should be fixed now - try again after reinstalling the package from GitHub
