### ISSUE TITLE
Error in hourly_fips

### ISSUE THREAD

**Issue by Arcticweasel** [leighseverson/countyweather#99]
Hello,

I'm currently trying to get hourly weather data for New York City, but always run into the following error.

```
Getting hourly weather data for New York County, New York. This may take a while.
Fehler: Can't subset columns that don't exist.
x The column `longitude` doesn't exist.
```
This is the code I used.

`df <- hourly_fips(fips = "36061", year = 2016, var = "temperature")`

I get the same error message when I try to run the example code.

```
ex <- hourly_fips("12086", coverage = 0.90, year = c(1994, 1995),
                   var = "temperature")
```
Can someone solve this?

Thank you in advance!

**Comment by nicholasoxford** [comment]
@Arcticweasel I will look at this later today. I am kinda shocked someone is actually using my code! 

You just motivated me to try to tackle this project again. I did this when I first started to really learn how to code.

**Comment by nicholasoxford** [comment]
https://github.com/nicholasoxford/WeatherV-GA

Try this out.

**Comment by nicholasoxford** [comment]
I need to work on that tutorial more, I raised an issue in the project about a year ago, and it was never taken care of.

**Comment by Arcticweasel** [comment]
Thank you very much. Unfortunately this won't help me in this case. Thank you anyway!

**Comment by leighseverson** [comment]
Hey there, try again after installing the package from GitHub - I think this should be fixed.
